### PR TITLE
update all last commit

### PR DESCRIPTION
**Pull request by ddkwork**

### CODE REVIEW

**Comment by rcoreilly** [comment]
It seems like your ddkwork:main is 27 commits behind the goki:main?  all of these changes are already in goki:main as far as I could tell.

**Comment by ddkwork** [comment]
> It seems like your ddkwork:main is 27 commits behind the goki:main? all of these changes are already in goki:main as far as I could tell.

I don't know why, except for the goki repository I can't use the following script to get the refresh code to avoid this problem, I don't have a lot of experience with git, how should I modify this script to avoid this problem?

```go
git remote add upstream https://github.com/goki/gide.git
git remote -v
git fetch upstream
git checkout main
git stash
git rebase upstream/main
git stash pop
```

**Comment by kkoreilly** [comment]
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by kkoreilly** [comment]
I would recommend doing one of the solutions suggested in the GItHub article I linked and not putting `pull.cmd` files in every repository. Also, you should not add `pull.cmd` to the `.gitignore`.

**Comment by ddkwork** [comment]
> 查看 https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

i will try

**Comment by ddkwork** [comment]
> I would recommend doing one of the solutions suggested in the GItHub article I linked and not putting files in every repository. Also, you should not add to the .`pull.cmd``pull.cmd``.gitignore`

Please send me the link address to see, thank you

**Comment by kkoreilly** [comment]
I meant the article I linked in the comment above (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork). You are correctly synced on taskmanager, but not on gide and files, so please try the steps in the article for those.

**Comment by ddkwork** [comment]
This PR is mainly to update github.com/go-delve/delve v1.21.2 to v1.22.0, otherwise there will be a compilation error

**Review by kkoreilly — CHANGES_REQUESTED** [review]
I will approve this once you remove the `pull.cmd` file and gitignore line and sync the fork from upstream using one of the methods described in the GitHub article I linked earlier in this PR.

**Comment by ddkwork** [comment]
> I will approve this once you remove the file and gitignore line and sync the fork from upstream using one of the methods described in the GitHub article I linked earlier in this PR.`pull.cmd`

I re-flashed the fork as you prompted, and after committing it found that the pr was inexplicably closed, I don't know what the reason is. I re-ran the PR, did you check that this time it was done correctly?

**Comment by kkoreilly** [comment]
I don't know why the PR was closed; the syncing of your fork probably closed it somehow. Can you redo your delve changes in a new PR rooted on the current main branch?

**Comment by ddkwork** [comment]
> I don't know why the PR was closed; the syncing of your fork probably closed it somehow. Can you redo your delve changes in a new PR rooted on the current main branch?

I don't know what's going on.,This time the compilation was successful after pulling and refreshing.,Wait for the next time I find something else and then pr it.

**Pull request closed without merging**
